#tomacat port
server:
  port: 9002
  #JSP to Modify Not Restart Server
  servlet:
    jsp:
      init-parameters:
        development: true
#jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://jeju.cvqasulqrodj.ap-northeast-2.rds.amazonaws.com:3306/finalproject?useSSL=false
    username: admin
    password: alsl8125+
    
#multipart
#  servlet:
#    multipart:
#      enabled: true
#      location: C:\Users\tkd97\git\jeju-back\FinalProjectSpringBoot\src\main\webapp\WEB-INF\photo
#      max-file-size: 100KB
#      max-request-size: 100KB